version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  cooldown:
    default-days: 7
  open-pull-requests-limit: 10
