language: java

jdk:
  - oraclejdk8

before-install:
  - if [ ! -z "$GPG_PRIVATE_KEY" ]; then echo $GPG_PRIVATE_KEY | base64 --decode | $GPG_EXECUTABLE --import; fi

deploy:
  provider: script
  skip_cleanup: true
  on:
    tags: true
    repo: colindean/keepachangelog-parser-java
  script: ./gradlew bintrayUpload

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
